site_name: "Notes: chanux.me"

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'red'

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: 'index.md'
  - Terraform:
    - The Basics: 'terraform/the-basics.md'
    - Automation Lessons: 'terraform/automation-lessons.md'
    - Workflow: 'terraform/workflow.md'
    - Exercise: 'terraform/exercise.md'
    - Tips: 'terraform/tips.md'
  - GCP:
    - Org: 'gcp/org.md'
    - SWAP: 'gcp/swap.md'
    - Tips: 'gcp/tips.md'
  - age: 'age.md'
  - Meta: 'meta.md'
