site_name: "Notes: chanux.me"

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'red'

markdown_extensions:
  - admonition
  - pymdownx.superfences

nav:
  - Home: 'index.md'
  - Terraform:
    - The Basics: 'terraform/the-basics.md'
    - Automation Lessons: 'terraform/automation-lessons.md'
    - Tips: 'terraform/tips.md'
  - GCP:
    - Tips: 'gcp/tips.md'
  - Meta: 'meta.md'
